console.log("%cSTOP RIGHT THERE", "background: red; font-size: 32px")
console.log("If you are looking for an HTML Developer, just reach out to me!")
console.log("I might even permanently work for you......")
console.log("")
console.log("Here's ways to reach me out")
console.log("Discord: ItsNeverLand#0001 or neverland#0001 (try both of them if one doesn't work)")
console.log("Emails: ytneverland@gmail.com")
// console.log("Emails: ytneverland@gmail.com and neverland@neverlandyt.wtf")
// console.log("Emails: ytneverland@gmail.com and neverland@neverlandyt.com")
// COMMENTED OUT DUE TO BEING NOT EXISTANT EMAILS (YET)
console.log("")
console.log("THANKS AND HAVE A GREAT DAY!")
console.log("%cNOTE: IF SOMEONE ASKED TO PASTE SOMETHING HERE, DON'T! IT COULD GRAB YOUR IP ADDRESS, OR BE A COOKIE LOGGER!", "background-color: red; font-size: 16px")